const mongoose = require("mongoose");

const { Schema } = mongoose;

/**
 * JudicialJudgment model
 *
 * Stores Supreme Court / High Court judgments (v1) with enough metadata for:
 * - latest lists (dashboard)
 * - universal search
 * - AI retrieval (RAG)
 */

const judicialJudgmentSchema = new Schema(
  {
    // Stable dedupe identifier (generated by makeDedupeKey)
    dedupeKey: { type: String, required: true, unique: true, index: true },

    // Official source identifier (when available)
    sourceId: { type: String, default: "", index: true },

    // Display / search fields
    title: { type: String, required: true, index: true, trim: true },
    court: { type: String, required: true, index: true, trim: true },
    bench: { type: String, default: "", trim: true },
    jurisdiction: { type: String, default: "", index: true, trim: true },

    // Parties / citation (optional)
    citation: { type: String, default: "", trim: true },
    parties: { type: String, default: "", trim: true },

    // Dates
    judgmentDate: { type: Date, default: null, index: true },
    publishedAt: { type: Date, default: null, index: true },
    effectiveDate: { type: Date, default: null, index: true },

    // Content
    // v1: store extracted plain text; can later add html/pdf fields
    contentText: { type: String, default: "" },
    contentHtml: { type: String, default: "" },

    // References / URLs
    sourceUrl: { type: String, default: "", trim: true },

    // State for update/remove duplicates
    status: {
      type: String,
      enum: ["active", "removed"],
      default: "active",
      index: true,
    },

    // Lightweight audit
    lastSeenAt: { type: Date, default: null, index: true },

    // Extra normalized metadata
    meta: { type: Schema.Types.Mixed, default: {} },
  },
  { timestamps: true }
);

judicialJudgmentSchema.index({ court: 1, jurisdiction: 1, judgmentDate: -1 });
judicialJudgmentSchema.index({ title: "text", contentText: "text" });

module.exports = mongoose.model("JudicialJudgment", judicialJudgmentSchema);

